library(sqldf)
library(lubridate)
png(filename = "plot4.png",
  width = 480, height = 480, units = "px")
household <- read.csv.sql('household_power_consumption.txt', sql = "select * from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep =";",stringsAsFactors=FALSE)
closeAllConnections()
household$datetime <- dmy_hms(paste(household$Date, household$Time))
par(mfrow = c(2, 2))
plot(household$datetime,  household$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)") 
plot(household$datetime,  household$Voltage, type="l", xlab="datetime", ylab="Voltage") 
with(household, plot(datetime, Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering"))
with(household, lines(datetime, Sub_metering_1, col = "black"))
with(household, lines(datetime, Sub_metering_2, col = "red"))
with(household, lines(datetime, Sub_metering_3, col = "blue"))
legend("topright", lty=c(1,1), col = c("black", "red", "blue"), legend = c("sub_metering_1", "sub_metering_2","sub_metering_3"))
plot(household$datetime,  household$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power") 
dev.off()